title: The Voice

description: >
  The Voice: Virginia Stillhard, Iris Bürgi und Nadja Büsser. Wir sind drei Cousinen, die ihre Leidenschaft zur Musik teilen. Musik ist für
  uns Passion, Energiequelle, die Möglichkeit abzuschalten, Balsam für die
  Seele, Freude, Spass und gibt uns ein Gefühl der Verbundenheit.
author: Virginia Stillhard, Iris Bürgi, Nadja Büsser
logo: /img/logo_the_voice.jpg

baseurl: ""
url: https://the-voice.cc

# Defaults
defaults:
  - scope:
      path: "" # anything
    values:
      layout: default

# Build settings
permalink: pretty
sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - README.md
include:
  - .htaccess
