title: The Voice

description: "The Voice: Virginia Stillhard, Iris B端rgi und Nadja B端sser."
author: Virginia Stillhard, Iris B端rgi, Nadja B端sser
logo: /img/logo_the_voice.jpg

baseurl: ""
url: https://the-voice.cc
google_site_verification: cg-_YXvoi698LDZ54SGNUu1iycqzrc8DDQNnR_trECI

# Defaults
defaults:
  - scope:
      path: "" # anything
    values:
      layout: default
      image: /img/logo_the_voice.jpg

# Build settings
permalink: pretty
sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - README.md
  - flake.*
include:
  - .htaccess
